# Generated by Django 3.2.14 on 2022-07-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('alias', models.CharField(max_length=1000, null=True)),
                ('birth_date', models.CharField(max_length=1000, null=True)),
                ('death_date', models.CharField(max_length=1000, null=True)),
                ('webpage', models.URLField(null=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uri', models.URLField()),
                ('size', models.IntegerField(null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('downloads', models.IntegerField(null=True)),
                ('license', models.URLField(null=True)),
                ('agents', models.ManyToManyField(to='api.Agent')),
                ('bookshelves', models.ManyToManyField(to='api.Bookshelf')),
                ('languages', models.ManyToManyField(to='api.Language')),
                ('resources', models.ManyToManyField(to='api.Resource')),
                ('subjects', models.ManyToManyField(to='api.Subject')),
            ],
            options={
                'ordering': ('-downloads',),
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
        migrations.AddField(
            model_name='agent',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agenttype'),
        ),
    ]
